import { useCallback, useEffect, useRef } from 'react';
import { useCommsStore } from '../store/commsStore';
import type { LatLon, TacticalMessage, TacticalSimEvent, TacticalUnit } from '../types';

/**
 * Two-way integration between the simulation engine and the comms subsystem.
 *
 * Outbound: combat events automatically generate the radio traffic a real net
 * would carry (contact reports, casualty reports, situation updates).
 *
 * Inbound: received messages drive the simulation - an intel report with a grid
 * reference spawns a hostile contact, a casualty report attrits a unit, and a
 * withdraw/retreat order changes a unit's behaviour.
 */

const COORD_PATTERN = /(-?\d{1,3}\.\d{3,})\s*[,/]\s*(-?\d{1,3}\.\d{3,})/;

function parseCoordinate(text: string): LatLon | null {
  const match = COORD_PATTERN.exec(text);
  if (!match) return null;
  const lat = Number(match[1]);
  const lon = Number(match[2]);
  if (Math.abs(lat) > 90 || Math.abs(lon) > 180) return null;
  return { lat, lon };
}

function findUnit(units: TacticalUnit[], needle: string): TacticalUnit | undefined {
  const target = needle.trim().toLowerCase();
  if (!target) return undefined;
  return units.find((u) => u.name.toLowerCase().includes(target) || u.id.toLowerCase() === target);
}

/** Applies a single inbound message to the simulated force disposition. */
function applyMessage(message: TacticalMessage, units: TacticalUnit[]): TacticalUnit[] | null {
  const haystack = `${message.subject} ${message.content} ${Object.values(message.fields).join(' ')}`;

  if (message.type === 'ORDER') {
    const orderType = (message.fields.orderType ?? haystack).toUpperCase();
    const target = findUnit(units, message.fields.unitTarget ?? '');
    if (!target) return null;
    if (/RETREAT|WITHDRAW|BREAK CONTACT/.test(orderType)) {
      return units.map((u) =>
        u.id === target.id ? { ...u, status: 'withdrawn' as const, route: [u.position] } : u
      );
    }
    const objective = parseCoordinate(message.fields.objective ?? haystack);
    if (objective) {
      return units.map((u) => (u.id === target.id ? { ...u, route: [u.position, objective] } : u));
    }
    return null;
  }

  if (message.type === 'INTEL') {
    const position = parseCoordinate(message.fields.location ?? haystack);
    if (!position) return null;
    const id = `intel-${message.id}`;
    if (units.some((u) => u.id === id)) return null;
    return [
      ...units,
      {
        id,
        name: message.fields.enemyType?.trim() || 'Reported Enemy Contact',
        affiliation: 'hostile',
        sidc: 'SHGPU-------', // Hostile ground unit, unknown type
        position,
        route: [position],
        status: 'active',
        strength: Number(message.fields.strength?.replace(/\D/g, '')) || 50,
      },
    ];
  }

  if (message.type === 'CASREP') {
    const target = findUnit(units, message.fields.unitTarget ?? message.senderCallsign);
    const casualties = Number(message.fields.casualtyCount?.replace(/\D/g, ''));
    if (!target || !casualties) return null;
    return units.map((u) => {
      if (u.id !== target.id) return u;
      const strength = Math.max(0, u.strength - casualties);
      return { ...u, strength, status: strength === 0 ? ('destroyed' as const) : u.status };
    });
  }

  return null;
}

export function useCommsIntegration(units: TacticalUnit[], onUnitsChange: (units: TacticalUnit[]) => void) {
  const identity = useCommsStore((state) => state.identity);
  const currentChannelId = useCommsStore((state) => state.currentChannelId);
  const sendMessage = useCommsStore((state) => state.sendMessage);
  const messages = useCommsStore((state) => state.messages);

  const unitsRef = useRef(units);
  unitsRef.current = units;
  const processedRef = useRef(new Set<string>());

  /** Turns a simulation event into the radio traffic a real net would carry. */
  const handleSimulationEvent = useCallback(
    (event: TacticalSimEvent) => {
      if (!identity) return;
      const grid = `${event.position.lat.toFixed(4)}, ${event.position.lon.toFixed(4)}`;
      const base = {
        urgency: 'IMMEDIATE' as const,
        recipientIds: [],
        channelId: currentChannelId,
        // Flagged so the inbound handler does not re-apply an event that the
        // simulation has already resolved.
        fields: { autoGenerated: 'true', location: grid },
      };

      switch (event.kind) {
        case 'CONTACT':
          void sendMessage({
            ...base,
            type: 'INTEL',
            subject: `Contact — ${event.unitName}`,
            content: `ALL STATIONS, THIS IS ${identity.callsign}. CONTACT. ${event.detail} GRID ${grid}. OVER.`,
            fields: { ...base.fields, enemyType: event.unitName, time: new Date().toISOString() },
          });
          break;
        case 'CASUALTY':
          void sendMessage({
            ...base,
            type: 'CASREP',
            subject: `Casualties — ${event.unitName}`,
            content: `${identity.callsign} CASREP. ${event.unitName} SUSTAINED ${event.casualties ?? 0} CASUALTIES AT GRID ${grid}. OUT.`,
            fields: {
              ...base.fields,
              casualtyCount: String(event.casualties ?? 0),
              wiaKia: 'ASSESSING',
              medevacRequired: (event.casualties ?? 0) > 10 ? 'YES' : 'NO',
            },
          });
          break;
        case 'DESTROYED':
          void sendMessage({
            ...base,
            type: 'SITREP',
            urgency: 'FLASH',
            subject: `${event.unitName} combat ineffective`,
            content: `FLASH. ${event.unitName} IS COMBAT INEFFECTIVE AT GRID ${grid}. OUT.`,
            fields: { ...base.fields, unitStatus: 'COMBAT INEFFECTIVE', currentPosition: grid },
          });
          break;
        default:
          void sendMessage({
            ...base,
            type: 'SITREP',
            urgency: 'ROUTINE',
            subject: `${event.unitName} movement`,
            content: `${identity.callsign} SITREP. ${event.detail} OUT.`,
            fields: { ...base.fields, unitStatus: 'ON THE MOVE', currentPosition: grid, assessment: event.detail },
          });
      }
    },
    [identity, currentChannelId, sendMessage]
  );

  // Inbound: let received messages drive the simulation.
  useEffect(() => {
    let next = unitsRef.current;
    let changed = false;
    // Oldest first so a sequence of orders is applied in the order it was sent.
    for (const message of [...messages].reverse()) {
      if (processedRef.current.has(message.id)) continue;
      processedRef.current.add(message.id);
      if (message.fields.autoGenerated === 'true') continue;
      const updated = applyMessage(message, next);
      if (updated) {
        next = updated;
        changed = true;
      }
    }
    if (changed) onUnitsChange(next);
  }, [messages, onUnitsChange]);

  return { handleSimulationEvent };
}
